packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: set this to true or false
  msw: set this to true or false
  protobufjs: set this to true or false
catalog:
  typescript: ^5.9.3
  typescript-eslint: ^8.59.2
  "@types/node": ^24.12.3
catalogs:
  code-formatting:
    prettier: ^3.8.3
    eslint: ^9.39.4
    eslint-config-prettier: ^10.1.8
  frontend:
    vite: ^7.3.3
  testing:
    vitest: ^4.1.5
