database:
  host: 'localhost'
  port: 5433
  database: 'groceries-dev'
  user: 'dev'
  password: 'dev'

schedule:
  cron: "0 3 * * *"

browser:
  headless: false

scrape:
  throttleBetweenPagesMs: 5000
  navigationTimeoutMs: 45000

retailers:
  - name: Woolworths
    enabled: true
    productByProduct: false
  - name: Coles
    enabled: true
    productByProduct: false
